In [49]:
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from time import time

In [50]:
%store -r X
X = X
%store -z

In [51]:
y = np.empty(X.shape[0])
y[0:954] = 0
y[954:1904] = 1
y[1904:2858] = 2
y[2858:X.shape[0]] = 3

X.shape, y.shape


((3812, 1083), (3812,))

In [2]:
#Splitting our dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=.33, shuffle=True, random_state=52
)

NameError: name 'train_test_split' is not defined

In [65]:
#Logistic Regression

lr_model = LogisticRegression(max_iter=2000)
param_dict = {'C': [0.001, 0.01, 0.1, 1, 10,100],
             'solver': ['liblinear','sag', 'lbfgs', 'saga']}

start = time()
grid_search = GridSearchCV(lr_model, param_dict)
grid_search.fit(X_train, y_train)
print("GridSearch took %.2f seconds to complete." % (time()-start))
display(grid_search.best_params_)
print("Cross-Validated Score of the Best Estimator: %.3f" % grid_search.best_score_)

GridSearch took 6.92 seconds to complete.


{'C': 100, 'solver': 'sag'}

Cross-Validated Score of the Best Estimator: 1.000


In [66]:
lr=LogisticRegression(C=100, solver ='sag',max_iter=2000)
lr.fit(X_train, y_train)
lr_preds=lr.predict(X_test)

print(confusion_matrix(y_test, lr_preds))
print(classification_report(y_test, lr_preds))
print("Accuracy Score: %.3f" % accuracy_score(y_test, lr_preds))

[[330   0   0   0]
 [  0 311   0   0]
 [  1   0 317   0]
 [  0   0   1 298]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       330
         1.0       1.00      1.00      1.00       311
         2.0       1.00      1.00      1.00       318
         3.0       1.00      1.00      1.00       299

    accuracy                           1.00      1258
   macro avg       1.00      1.00      1.00      1258
weighted avg       1.00      1.00      1.00      1258

Accuracy Score: 0.998


This logistic regression model is extremely accurate, likely because of the impact of certain identifier words such as the title names in the strings. A further way to optimize the model for identification would be to remove these titles from the section strings in order to test the reliability of the model in the absence of the section titles.

In [63]:
%store X

Stored 'X' (csr_matrix)
